FROM ghcr.io/tpm2-software/ubuntu-18.04

RUN python3 -m pip install -U pip setuptools wheel virtualenv

COPY .ci/download-deps.sh /workspace/tpm2-pytss/.ci/download-deps.sh

RUN bash -c 'source /workspace/tpm2-pytss/.ci/download-deps.sh && get_deps /workspace'

ENV TSS2_LOG=all+trace

WORKDIR /workspace/tpm2-pytss
