name: Publish Github Pages

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        python3 -m pip install --user --upgrade pip
        python3 -m pip install --user --upgrade twine
        docker build -t tpm2software/tpm2-tss-python -f .ci/Dockerfile.tpm2-tss-python .

    - name: Test
      env:
        TEST: 1
      run: ./.ci/run.sh

    - name: Publish to GH Pages
      env:
        PUBLISH_DOCS: 1
        SSH_TPM2_PYTSS_GH_PAGES: ${{ secrets.SSH_TPM2_PYTSS_GH_PAGES }}
      run: ./.ci/run.sh
